# Generated by Django 4.2.3 on 2023-07-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='realestate',
            name='area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realestate',
            name='mail',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='realestate',
            name='numofbathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realestate',
            name='numofbedroom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realestate',
            name='prict',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realestate',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
