# Generated by Django 4.2.3 on 2023-07-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_realestate_address_realestate_area_realestate_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='picture',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
