# Generated by Django 4.2.3 on 2023-07-04 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_realestate_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realestate',
            old_name='prict',
            new_name='price',
        ),
    ]
